// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8hQouuo41NMIKSpMeyMoewTRmMK4hQc',
    appId: '1:838474786972:web:813007c48abdb07cb8a559',
    messagingSenderId: '838474786972',
    projectId: 'zygig-shop',
    authDomain: 'zygig-shop.firebaseapp.com',
    storageBucket: 'zygig-shop.firebasestorage.app',
    measurementId: 'G-HRK2CF5B81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzx6G5m3jrwmYeoPhKvc4rNW4sgtMbWm0',
    appId: '1:838474786972:android:b73b17c9a6b6ad42b8a559',
    messagingSenderId: '838474786972',
    projectId: 'zygig-shop',
    storageBucket: 'zygig-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Q5IKZgMvGDucliC7F51tSZ0MX_7HnZI',
    appId: '1:838474786972:ios:9730257c598688feb8a559',
    messagingSenderId: '838474786972',
    projectId: 'zygig-shop',
    storageBucket: 'zygig-shop.firebasestorage.app',
    iosBundleId: 'com.example.zygig',
  );
}
